### ISSUE TITLE
Publicize JsonValue So It Can Be Passed Around

### ISSUE THREAD

**Issue by ghost** [berdon/zig-json#5]
My zig is rusty so I'm probably just holding it wrong, but when trying to pass a JsonValue around the compiler errors out complaining that JsonValue isn't marked as pub.

An obvious case for this is json of the form
```
{
    "type": "some_understood_type",
    "payload": {....}
}
```
where I'd probably want to switch on type and feed root.payload into various handlers.

**Comment by berdon** [comment]
I'm not ignoring this - been out at a conference the past week and haven't had time to properly dig in.

**Comment by ghost** [comment]
No worries! I have another branch over on my account which publicizes JsonValue and it doesn't *seem* to break anything. I think it's branched off of my fix for building on 0.12 but since it's literally a one line change it's probably not worth opening a PR for anyway.

**Comment by ghost** [comment]
While I've got you here anyway: do you mind PRs via e-mail? I might knock deep equality together when I have a bit of time and I really don't like github c:

**Comment by berdon** [comment]
Up to you 👍; I appreciate the PRs however they manifest.

**Comment by berdon** [comment]
Should be fixed btw.

**Comment by berdon** [comment]
@tekktonic Have you had a chance to test this? It should be fixed but wanted to check in since you've been recent active.

**Comment by ghost** [comment]
Hey, I'll try to get to it this weekend if I can. It's been a busy week for me due to family things :)

**Comment by ghost** [comment]
Correction: next week. I forgot that the code I wrote this patch for originally is on my desktop, I'm currently on the other side of the state.

**Comment by ghost** [comment]
merged PR looks good to me. Just got back in last night :+1:
